/* Generated By:JavaCC: Do not edit this line. SieveParserConstants.java */
package com.surfront.sieve.parser;

public interface SieveParserConstants {

  int EOF = 0;
  int SINGLE_LINE_COMMENT = 8;
  int MULTI_LINE_COMMENT = 9;
  int NUMBER = 11;
  int IDENTIFIER = 12;
  int TAG = 13;
  int STRING = 14;
  int ALPHA = 15;
  int DIGIT = 16;
  int ESCAPE = 17;

  int DEFAULT = 0;
  int IN_SINGLE_LINE_COMMENT = 1;
  int IN_MULTI_LINE_COMMENT = 2;

  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\r\"",
    "\"\\n\"",
    "\"\\f\"",
    "\"#\"",
    "\"/*\"",
    "<SINGLE_LINE_COMMENT>",
    "\"*/\"",
    "<token of kind 10>",
    "<NUMBER>",
    "<IDENTIFIER>",
    "<TAG>",
    "<STRING>",
    "<ALPHA>",
    "<DIGIT>",
    "<ESCAPE>",
    "\";\"",
    "\"{\"",
    "\"}\"",
    "\"(\"",
    "\",\"",
    "\")\"",
    "\"[\"",
    "\"]\"",
  };

}
